logging:
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    root: info

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  servlet:
    context-path: /community

spring:
  application:
    name: community-site-back-team2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Abcd1234!
    url: jdbc:mysql://15.165.171.40/community
    username: myuser

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  # ??? ??
  mail:
    host: smtp.gmail.com
    port: 587
    username: skdlawo5985@gmail.com
    password: rgwi bqmz ybah pkjo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    # JPA ??
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      location: uploads/
      max-file-size: 10MB
      enabled: true


jwt:
  issuer: chhak0503@gmail.com
  secret: 4XudNUpSmog3lwI9thJFejF7YfBB0517

# 파일 업로드 설정
file:
  upload:
    path: uploads/
